Issue #12 gelöst
JoJotoPlay/kinoa pull request #17
Opened 2020-11-24 10:55 UTC by Levana-Fallboehmer

Erstellen der Film-Seite, Links sind noch nicht verlinkt, feste Filmbeispiele eingebunden

2020-11-24 19:26 UTC, Fl0rianSchmitt requested changes
Header bitte anpassen

2020-11-25 16:45 UTC, annekr submitted a review, later dismissed

2020-11-26 08:00 UTC, Fl0rianSchmitt reviewed
Alles fertig

2020-11-26 08:01 UTC, Fl0rianSchmitt approved these changes
Änderungen Vorgenommen

2020-11-26 10:04 UTC, Fl0rianSchmitt approved these changes

2020-11-26 10:06 UTC, merged